### ISSUE TITLE
Не могу заставить работать на Debian 7

### ISSUE THREAD

**Issue by ASMfreaK** [mdevaev/emonoda#39]
Ставил Emonoda на свой сервер на OpenMediaVault.
Сказал в консоли от рута и консоль мне ответила:
```bash
# pip install  emonoda
Downloading/unpacking emonoda
  Downloading emonoda-1.9.31.tar.gz (43Kb): 43Kb downloaded
  Running setup.py egg_info for package emonoda
    
Requirement already satisfied (use --upgrade to upgrade): chardet in /usr/local/lib/python2.7/dist-packages (from emonoda)
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /usr/local/lib/python2.7/dist-packages (from emonoda)
Requirement already satisfied (use --upgrade to upgrade): colorama in /usr/local/lib/python2.7/dist-packages (from emonoda)
Requirement already satisfied (use --upgrade to upgrade): pygments in /usr/local/lib/python2.7/dist-packages (from emonoda)
Requirement already satisfied (use --upgrade to upgrade): pytz in /usr/local/lib/python2.7/dist-packages (from emonoda)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/local/lib/python2.7/dist-packages (from emonoda)
Requirement already satisfied (use --upgrade to upgrade): Mako in /usr/local/lib/python2.7/dist-packages (from emonoda)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /usr/local/lib/python2.7/dist-packages (from python-dateutil->emonoda)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe>=0.9.2 in /usr/local/lib/python2.7/dist-packages (from Mako->emonoda)
Installing collected packages: emonoda
  Running setup.py install for emonoda
    SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/dist-packages/emonoda/cli.py', 55, 18, '        self.print("# {green}I{reset}: " + text, *args, **kwargs)\n'))
    
    SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/dist-packages/emonoda/apps/emdiff.py', 64, 28, '            log_stdout.print(*fmt.format_torrents_diff(diff, " "))\n'))
    
    SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/dist-packages/emonoda/apps/emfile.py', 123, 13, '    log.print("{blue}Path:{reset}          %s", (torrent.get_path(),))\n'))
    
    SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/dist-packages/emonoda/apps/emfetch.py', 151, 30, '        self._log_stdout.print(*self._format_fail("red", "!", "INVALID_TORRENT"))\n'))
    
    SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/dist-packages/emonoda/apps/emfind.py', 92, 28, '            log_stdout.print(line, (path,))\n'))
    
    SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/dist-packages/emonoda/apps/emrm.py', 67, 36, '                    log_stdout.print("{yellow}%s{reset} -- %s", (torrent_hash, name))\n'))
    
    SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.7/dist-packages/emonoda/helpers/surprise.py', 34, 21, '            log.print("%s", ("\\n".join("\\t" + row for row in traceback.format_exc().strip().split("\\n")),))\n'))
    
    
    Installing emdiff script to /usr/local/bin
    Installing emfile script to /usr/local/bin
    Installing emhook-manage-trackers script to /usr/local/bin
    Installing emload script to /usr/local/bin
    Installing emrm script to /usr/local/bin
    Installing emfetch script to /usr/local/bin
    Installing emfind script to /usr/local/bin
Successfully installed emonoda
Cleaning up...
```

Вывод  команд, которые могут заинтересовать:
```bash
# uname -a
3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u6 x86_64 GNU/Linux
# python
Python 2.7.3 (default, Mar 13 2014, 11:03:55) 
[GCC 4.7.2] on linux2
```
Прошу помощи. У меня на сервере работает демон Transmission. Если я сделаю Docker-картинку Emonoda и дам этой картинке доступ к localhost:9091, будет ли такая связка работать? Фактически - будет ли Emonoda работать удалённо, если в качестве клиента у неё будет демон Tranmission?

**Comment by mdevaev** [comment]
Привет! Вам нужен python 3.4 или 3.5, на второй ветке программа не работает.
Касаемо второго вопроса. Я так понял, что трансмишн тоже в докере работает? Вообще, у меня самого rtorrent сидит в докере, а emonoda стоит на самой машине. Чтобы такое работало, нужно пробросить порт и сделать так, чтобы пути к данным и каталогу с торрентами совпали для обоих контейнеров. То есть, чтобы в emonoda опция `client/torrents_dir` выглядела бы так же, как и для трансмишна. Точно так же с `client/data_root_dir`.

**Comment by ASMfreaK** [comment]
Нет. Transmission у меня просто в основной ОС стоит, но у меня уже есть куча всего, что работает в контейнерах, так что можно просто добавить ещё один. Но, в любом случае, emonoda должна находится с Transmission на одном компьютере? Т.е. ей недостаточно интерфейса RPC?
Есть предложение написать о требованиях  к системе в `README.md`, чтобы в будущем у других людей не возникало вопросов. Или может я невнимально читал?

**Comment by mdevaev** [comment]
Там сверху ридми висит большой лейбл: [![Python Versions](https://img.shields.io/pypi/pyversions/emonoda.svg)](https://pypi.python.org/pypi/emonoda/). Но вообще я сейчас потихоньку делаю подробную документацию, так что дополню где-нибудь большими красными буквами :-)
Emfetch как нужен еще каталог с торрент-файлами. Я сейчас перечитал, как у меня плагин к трансмишну устроен - там торренты загружаются в клиент потоком байтов, прочитанных из файла, так что совпадение путей не обязательно.
А вот чтобы завести какой-нибудь emfind, надо будет пробросить еще и каталог с данными.

**Comment by mdevaev** [comment]
Ну как, работает?

**Comment by ASMfreaK** [comment]
Пока не запускал. Тут пока реал навалился. Проблема решается установкой правильной версии Python, Над контернером для emonoda работаю.
Спасибо за помощь

**Comment by ASMfreaK** [comment]
Чтобы правильно запустилось, нужно скачать, распаковать исходники от Python 3.5, собрать 
```
./configure
make
make altinstall
```
После этого в системе появляются python3.5 и pip3.5, которыми надо устанавливать и запускать emonoda.

**Comment by mdevaev** [comment]
Ага, то есть нормально работает?
