### ISSUE TITLE
Нужны алиасы для трекеров

### ISSUE THREAD

**Issue by omgiafs** [mdevaev/emonoda#41]
Например один и тот же rutor.org сидит на доменах rutor.lib, freedom-tor.org, rutor.is, rutor.info (редирект на freedom-tor.org), rutorc6mqdinc4cz.onion

Под каждый домен плагин писать, конечно, можно, но "Шура, это же не наш метод" ©.
Как по мне, надо переменную PLUGIN_NAME класса Plugin сделать списком с перечислением всех возможных доменных имен трекера. Так будет легко редактировать все изменения в доменах.
Ну или еще как-то вывернуться, я код буквально минуту наблюдал.

**Comment by mdevaev** [comment]
Да, так можно сделать. Нонейм с ipv6 примерно так и работает. Посмотрю.

**Comment by omgiafs** [comment]
Спасибо!
С наступающим (или наступившим! :)

**Comment by mdevaev** [comment]
И вас тоже)

**Comment by mdevaev** [comment]
Сделал алиасы для плагинов, чтобы не менять конфигурацию при обновлении. Смысла делать настраиваемые домены нет, так как все равно их все блокируют.
