### ISSUE TITLE
Emfind принимает за Orphans переименованные файлы

### ISSUE THREAD

**Issue by YurikaL** [mdevaev/emonoda#58]
Если изменить имя файла или каталога из раздачи изнутри торрент-клиента (Transmission), `emfind orphans` будет считать переименованный файл не принадлежащим ни одной из раздач, даже если перегенерировать кэш при помощи `emfile rebuild-cache`.

В более широком смысле всё выглядит так, будто бы orphans начинают считаться те файлы, имя которых не совпадают с выводом `emfile --provides` - так, например, в orphans попадает файл, имя которого в `emfile --provides` почему-то отображается кракозябрами (хотя в самом клиенте всё в порядке).

**Comment by mdevaev** [comment]
Дело в том, что сейчас кэш строится на основе содержимого торрент-файла, а не по данным клиента.

У меня сейчас нет инсталляции с transmission, но кажется, что это можно легко поправить. Попробуйте изменить в файле `emonoda/helpers/datacache.py` строчку 126 с:
`files=torrent.get_files(),`
на:
`files=client.get_files(torrent),`
Отступ пробелами сохраните на том же уровне.

Потом попробуйте перестроить кеш. Если все будет в порядке и переименованные файлы заработают - я сделаю опцию, чтобы сохранить это поведение. Если нет - ну, буду думать, как пофиксить)

**Comment by YurikaL** [comment]
Помогло идеально, спасибо! Все переименованные файлы распознались как следует. Ждём релиз с опцией!

**Comment by mdevaev** [comment]
На здоровье)
Облагородил. Поставьте в конфиге `emfind/files_from_client=true`, и будет вам счастье.
http://mdevaev.github.io/emonoda/emfind/#_3

**Comment by YurikaL** [comment]
Всё работает. Спасибо ещё раз!
