### ISSUE TITLE
Возможность возврата на раздачу, при наличии уже скачанных данных

### ISSUE THREAD

**Issue by dmitrysdm** [mdevaev/emonoda#61]
Имеется масса уже скачанных данных, и, есть желание вернуться на раздачу, т.е. нужно, чтобы скрипт просканировал директорию ( полагаю, что размера и имени файлв достаточно ), после чего самостоятельно нашел трекер и подключился к раздаче.

**Comment by mdevaev** [comment]
Привет. Это случайно не ваш тред?)
https://www.linux.org.ru/forum/talks/15609801

Автоматически этого не сделать без сведений о том, как вы раскладывали свои файлы по каталогам. Посмотрите https://mdevaev.github.io/emonoda/emload

**Comment by dmitrysdm** [comment]
Да, мой.
Спасибо за ответ.
