### ISSUE TITLE
Как быть с https в client/url ?

### ISSUE THREAD

**Issue by paulz1** [mdevaev/emonoda#70]
Возможно, что я что-то просто не понимаю.

Пытаюсь работать с emonoda на машине, где уже установлен rtorrent и rutorrent.

1) Если не указывать **client/url** по умолчанию используется **http://localhost/RPC2**
и я получаю `xmlrpc.client.ProtocolError: <ProtocolError for localhost/RPC2: 301 Moved Permanently>`

Причина, я так понимаю, что http перенапрявляется на https

2) если установить **client/url** на **https://localhost/RPC2**
То получаем в итоге `ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'localhost'. (_ssl.c:1056)`

Можно ли как-то обойти (disable) проверку сертификата ?
Или, может быть, я вообще что-то не так понимаю.

**Comment by mdevaev** [comment]
Быстрее всего будет отключить редирект для подключения по локалхосту и подключаться по http

**Comment by paulz1** [comment]
Ммм... я не админ сервера. У меня нет таких полномочий, и если просить - то наверняка, админ откажет.

**Comment by mdevaev** [comment]
Возьмите свежую версию из гита. Я добавил опцию `verify: false`, укажите ее рядом с `url` в секции плагина.

**Comment by paulz1** [comment]
Супер! Спасибо большое. Сегодня попробую и доложу как работает. :-)

**Comment by paulz1** [comment]
Спасибо, опция работает.

Ну, мне в итоге все равно не очень помогло, потому что через localhost ничего в итоге не работает, поэтому пришлось через внешний адрес подключаться (а там с сертификатом все ок). Но думаю, что опцию отключения проверки ssl иметь полезно.

Прежде чем закрывать issue две небольшие ремарки

1) на внешнем адресе у меня стоит http basic auth может быть стоит в документации указать, что если она нужна, то ее можно указать в URL https://user:password@host/RPC2

2) и маленький вопрос.
В ruTorrent я использую опцию Label c помощью, которой можно расставлять теги на разные торренты.
Можно ли как-нибудь с помощью emonoda выцепить эту информацию ?

Спасибо еще раз за помощь.

**Comment by mdevaev** [comment]
Метку можно показывать:
```yaml
emfile:
    show_customs: c1

emupdate:
    save_customs: c1
```

**Comment by paulz1** [comment]
Ага, спасибо. Все работает, метки видно.

**Comment by mdevaev** [comment]
Ну и отличненько)
