### ISSUE TITLE
Не работает rutor и rutracker

### ISSUE THREAD

**Issue by nedden1988** [mdevaev/emonoda#71]
Рутор и рутрекер не работают. Проблема в том, что они не проходят fingerprint
Нужно поправить файлы:
1) https://github.com/mdevaev/emonoda/blob/master/trackers/rutor.info.json
2) https://github.com/mdevaev/emonoda/blob/master/trackers/rutracker.org.json

Для проверки сделал копию репы и поправил эти файлы.
Локально в файле /emonoda/plugins/__init__.py прописал свою репу.
Запустил emupdate. Все работает

**Comment by mdevaev** [comment]
Поправил, сегодня соберу релиз.
