### ISSUE TITLE
build fails against setuptools 68.0.0

### ISSUE THREAD

**Issue by stanislavlevin** [mdevaev/emonoda#72]
Build fails against `setuptools` `68.0.0` with:
```
+ /usr/bin/python3 setup.py build
Traceback (most recent call last):
  File "/usr/src/RPM/BUILD/emonoda-2.1.36/setup.py", line 146, in <module>
    main()
  File "/usr/src/RPM/BUILD/emonoda-2.1.36/setup.py", line 68, in main
    setuptools.command.easy_install.get_script_args = _ScriptWriter.get_script_args
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object '_ScriptWriter' has no attribute 'get_script_args'. Did you mean: '_get_script_args'?
```

`setuptools` `68.0.0` introduced many breaking changes https://setuptools.pypa.io/en/stable/history.html#v68-0-0
one of them:
> pypa/setuptools#3948: Remove deprecated APIs in easy_install: get_script_args, get_script_header and get_writer. The direct usage of easy_install has been deprecated since v58.3.0, and the warnings regarding these APIs predate that version.

**Comment by mdevaev** [comment]
Thanks!
