### ISSUE TITLE
Добавьте возможность выбирать проксировать ли dns 

### ISSUE THREAD

**Issue by ASMfreaK** [mdevaev/emonoda#73]
В связи с текущей неразберихой с rutracker, хотелось бы иметь возможность отключать проксирование dns-запросов. 
Сейчас я починил это у себя локально так:

```
sed -i 's/rdns: bool=True/rdns: bool=False/g' /путь/до/site-packages/emonoda/web/sockshandler.py
```

Хотелось бы иметь возможность это настраивать из конфига.

**Comment by mdevaev** [comment]
Проверьте из гита, если все норм - соберу в релиз.

**Comment by mdevaev** [comment]
Все нормально работает?

**Comment by ASMfreaK** [comment]
Сегодня вечером проверю, отпишусь. Спасибо за быстрый фикс

**Comment by mdevaev** [comment]
Пожалуйста. Буду ждать.

**Comment by ASMfreaK** [comment]
Работает и так и так :+1:

**Comment by mdevaev** [comment]
Оч хорошо. Тогда в релиз.
