### ISSUE TITLE
Выпуск внешнего плагина конфетти для Home Assistant

### ISSUE THREAD

**Issue by asmfreak** [mdevaev/emonoda#76]
Я выпустил первую версию плагина конфетти для Home Assistant. Было бы неплохо выпустить версию emonoda c PR #74 , чтобы в плагине минимально совместимую версию указать.
Вот ссылка на плагин: https://github.com/ASMfreaK/emonoda-plugin-confetti-hass

**Comment by mdevaev** [comment]
Привет. Сорри, я совсем замотался с работой. Посмотрю на днях.
